### ISSUE TITLE
"Software" link for the webseite and mentioning of open source

### ISSUE THREAD

**Issue by nuest** [enviroCar/enviroCar-www#214]
There is not enough information on the website the the software is available on GitHub as _open source_. Ideas to change this:

* mention the fact on the about page
* add a first level menu entry "software" which includes links to the sources and description of the software components

@ahitch - what do you think?

**Comment by nuest** [comment]
The software link does only appear after login, though it is outside of the "if logged in" code:
https://github.com/enviroCar/enviroCar-www/blob/12497e61018ddad6450084fa9795ac4f77422dc3/header.php#L175

**Comment by ahitch** [comment]
can anyone fix this?
